os: linux
language: node_js
node_js:
  - node

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

jobs:
  include:
    
    - stage: Test
      name: 'Unit Test'
      install: npm install
      script: docker-compose run server npm run test

    - stage: Deploy
      name: 'Deploy to Staging'
      script:
        - docker-compose build
      deploy:
      - provider: script
        script:
          docker tag microci-throwaway_server $DOCKER_USERNAME/microci-throwaway_server:latest;
          docker push $DOCKER_USERNAME/microci-throwaway_server:latest;
          docker images
      - provider: script    
        script:
          docker tag microci-throwaway_server registry.heroku.com/$HEROKU_APP/web;
          heroku container:login;
          docker push registry.heroku.com/$HEROKU_APP/web;
          heroku container:release web --app $HEROKU_APP
