os: linux
language: node_js
node_js:
  - node
cache: npm

services: docker
before_install: 
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

before_script:
  - docker tag $DOCKER_USERNAME/microci-throwaway_server registry.heroku.com/microci-test/web;
  
script:
  - docker push registry.heroku.com/$HEROKU_APP/web;
  - heroku container:release web --app $HEROKU_APP;