os: linux
language: node_js
node_js:
- node
cache: npm
jobs:
  include:
  - stage: Build
    name: Build Container Image
    services: docker
    script:
    - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - docker-compose build
    - docker tag microci-throwaway_server "$DOCKER_USERNAME"/microci-throwaway_server:latest
    - docker push "$DOCKER_USERNAME"/microci-throwaway_server
    - docker images
  - stage: Deploy(Staging)
    name: Deploy To Staging
    deploy:
      provider: script
      script: bash deploy.sh
  
