os: linux
language: node_js
node_js:
- node
cache: npm
jobs:
  include:
  - stage: Test
    install: npm install
    name: Unit Test
    script: npm test
  - stage: Build
    name: Build Container Image
    services: docker
    provider: script
    script:
      # Authenticate to Docker Hub
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      # Build and push image
      - docker-compose build
      - docker ps -all
      - docker tag ci-cd-dupe_server "$DOCKER_USERNAME"/ci-cd-dupe_server:latest
      - docker push "$DOCKER_USERNAME"/ci-cd-dupe_server
      - docker images
  - stage: Deploy(Staging)
    name: Deploy To Staging
    deploy:
      provider: script
      script:
        # Authenticate to Docker Hub and pull the latest image
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - docker pull "$DOCKER_USERNAME"/ci-cd-dupe_server:latest
        # Deploy image to Heroku
        - heroku container:login
        - docker tag ci-cd-dupe_server registry.heroku.com/microci-test/web
        - docker push registry.heroku.com/microci-test/web
        - heroku container:push web
        - heroku container:release web