os: linux
language: node_js
node_js:
  - node
services: docker
cache: npm

before_install:
  # Login to Docker Hub and pull image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_TOKEN" docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com

install: 
  - npm install -g heroku

script:
  - docker pull $DOCKER_USERNAME/microci-throwaway_server:latest
  - docker tag $DOCKER_USERNAME/microci-throwaway_server registry.heroku.com/$HEROKU_APP/web
  - docker images

deploy:
  provider: script
    docker push registry.heroku.com/microci-test/web;
    heroku container:release web --app $HEROKU_APP;
    docker logout;
