os: linux

jobs:
  include:
    - stage: Build
      name: 'Build Container Image'
      services: docker
      env:
        - DOCKER_COMPOSE_VERSION=3.7
      before_install:
        - docker-compose build
        - docker ps
    