os: linux
language: node_js
node_js:
  - node
services: docker
cache: npm

install: 
  - npm install -g heroku

before_script:
  # Login to Docker Hub and pull image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - heroku container:login
