os: linux
language: node_js
node_js:
  - node
services: docker
cache: npm

install: 
  - npm install -g heroku

before_script:
  # Login to Docker Hub and pull image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_TOKEN" docker login --username=_ --password-stdin registry.heroku.com

script:
  - docker pull $DOCKER_USERNAME/microci-throwaway_server:latest
  - docker tag $DOCKER_USERNAME/microci-throwaway_server registry.heroku.com/$HEROKU_APP/web
  - docker images

deploy:
  provider: script
    script:
      - docker push registry.heroku.com/$HEROKU_APP/web
      - heroku container:release web --app $HEROKU_APP
      - docker logout
