os: linux
language: node_js
node_js:
- node
cache: npm
jobs:
  include:
  - stage: Test
    install: npm install
    name: Unit Test
    script: npm test
  - stage: Build
    name: Build Container Image
    services: docker
    before_script:
      # Authenticate to Docker Hub
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    script:
      # Build image
      - docker-compose build
      - docker tag microci-throwaway_server "$DOCKER_USERNAME"/microci-throwaway_server:latest
  - stage: Deploy(Staging)
    name: Deploy To Staging
    deploy:
      provider: script
      before_script:
        # Authenticate to heroku container registry
        - echo "${HEROKU_AUTH_TOKEN}" | docker login --username="$DOCKER_USERNAME" --password-stdin registry.heroku.com
      script:
        # Deploy image to Docker Hub
        - docker images
        - docker push "$DOCKER_USERNAME"/microci-throwaway_server
        # Deploy image to Heroku Registry
        - docker tag microci-throwaway_server registry.heroku.com/microci-test/web
        - heroku container:release web --app $HEROKU_APP

      