os: linux
language: node_js
node_js:
- node
cache: npm

jobs:
  include:
  - stage: Build
    name: Build Container Image
    services: docker
    script:
      # Authenticate to Docker Hub
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      # Build and push image
      - docker-compose build   
      - docker tag microci-throwaway_server "$DOCKER_USERNAME"/microci-throwaway_server:latest
      - docker push "$DOCKER_USERNAME"/microci-throwaway_server
      - docker images
  - stage: Deploy(Staging)
    name: Deploy To Staging
    services: docker
    deploy:
      provider: script
      before_script: 
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      script:
        - docker pull "$DOCKER_USERNAME"/microci-throwaway_server:latest
        # Deploy image to Heroku
        - echo "${HEROKU_AUTH_TOKEN}" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com
        - docker tag "$DOCKER_USERNAME"/microci-throwaway_server registry.heroku.com/microci-test/web
        - docker images
        - docker push registry.heroku.com/microci-test/web        
        - heroku container:release web