os: linux
language: node_js
node_js:
- node

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

after_success:
  script:
    - docker-compose build
    - docker tag microci-throwaway_server registry.heroku.com/$HEROKU_APP/web;
    - docker push registry.heroku.com/$HEROKU_APP/web;
    - heroku container:release web --app $HEROKU_APP;